- id: golang-best-practices-check
  name: Golang Best Practices Check
  entry: ./golang_best_practices_check
  language: golang
  files: \.go$
  pass_filenames: true
  always_run: false
  stages: [pre-commit]
